general {
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

# Screenlock
listener {
    # HYPRLOCK TIMEOUT
    timeout = 600
    # HYPRLOCK ONTIMEOUT
    on-timeout = wallock -o lock
}

